name: CD

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release type'
        required: true
        default: 'patch'
        type: choice
        options:
          - 'patch'
          - 'minor'
          - 'major'
  push:
    branches: [main]
    paths-ignore:
      - 'README.md'
      - '.github/workflows/upstream-baseimage.yaml' # Optional, don't retrigger on upstream checker

jobs:
  create-gh-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.calculate.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Calculate next version
        id: calculate
        env:
          VERSION_TYPE: ${{ github.event.inputs.release_type || 'patch' }}
        run: |
          latest_tag_version=$(git tag --sort=committerdate --list | tail -1)
          latest_version=${latest_tag_version#v}
          if [[ -z "$latest_version" ]]; then
            latest_version="0.0.0"
          fi
          latest_major_version=$(echo $latest_version | cut -d "." -f 1)
          latest_minor_version=$(echo $latest_version | cut -d "." -f 2)
          latest_patch_version=$(echo $latest_version | cut -d "." -f 3)
          if [[ "$VERSION_TYPE" == "major" ]]; then
              next_version="$(($latest_major_version + 1)).0.0"
          elif [[ "$VERSION_TYPE" == "minor" ]]; then
              next_version="${latest_major_version}.$(($latest_minor_version + 1)).0"
          else
              next_version="${latest_major_version}.${latest_minor_version}.$(($latest_patch_version + 1))"
          fi
          echo "version=$next_version" >> $GITHUB_OUTPUT

      - name: Check if tag already exists
        id: check_tag
        run: |
          git fetch --tags
          if git rev-parse "refs/tags/v${{ steps.calculate.outputs.version }}" >/dev/null 2>&1; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Create release
        if: steps.check_tag.outputs.exists == 'false'
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ steps.calculate.outputs.version }}
          generateReleaseNotes: true

  update_changelog:
    name: Update Changelog and config.yaml
    needs: create-gh-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y yq gh

      - name: Update CHANGELOG.md and config.yaml
        working-directory: ntfy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: v${{ needs.create-gh-release.outputs.version }}
        run: |
          RELEASE_NOTES=$(gh release view "${TAG}" --json body -q .body)
          git checkout -b "automated/update-changelog-${TAG}"
          { echo -e "# Release ${TAG}\n\n${RELEASE_NOTES}\n\n"; cat CHANGELOG.md; } > CHANGELOG.tmp
          mv CHANGELOG.tmp CHANGELOG.md
          yq e --inplace ".version = \"${TAG}\"" config.yaml
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add CHANGELOG.md config.yaml
          git commit -m "Update changelog for release ${TAG}"
          git push --set-upstream origin "automated/update-changelog-${TAG}"
          gh pr create --title "Update changelog for release ${TAG}" --body "This PR updates the changelog."
          gh pr merge --merge --auto "automated/update-changelog-${TAG}"

  docker:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    env:
      IMAGE_OWNER: ghcr.io/michalchecinski
      TAG: ${{ needs.create-gh-release.outputs.version }}
    needs: create-gh-release
    strategy:
      fail-fast: false
      matrix:
        arch:
          - { docker_name: amd64, hass_name: amd64 }
          - { docker_name: arm64, hass_name: aarch64 }
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v5
        with:
          context: ./ntfy
          push: true
          platforms: linux/${{ matrix.arch.docker_name }}
          build-args: |
            BUILD_VERSION=${{ env.TAG }}
            BUILD_ARCH=${{ matrix.arch.hass_name }}
          tags: |
            ${{ env.IMAGE_OWNER }}/ntfy-ha-addon${{ matrix.arch.hass_name }}:${{ env.TAG }}
            ${{ env.IMAGE_OWNER }}/ntfy-ha-addon${{ matrix.arch.hass_name }}:latest
